// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package models

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for LogStatusStatus.
const (
	Done       LogStatusStatus = "done"
	Failed     LogStatusStatus = "failed"
	NotStarted LogStatusStatus = "not_started"
	Started    LogStatusStatus = "started"
)

// LogStart defines model for LogStart.
type LogStart struct {
	Id          openapi_types.UUID `json:"id"`
	LocalConfig *bool              `json:"local_config,omitempty"`
	MaxSize     *int32             `json:"max_size,omitempty"`
	RotatedLogs *bool              `json:"rotated_logs,omitempty"`
}

// LogStatus defines model for LogStatus.
type LogStatus struct {
	Status LogStatusStatus `json:"status"`
}

// LogStatusStatus defines model for LogStatus.Status.
type LogStatusStatus string

// GetV1OperationsLogDownloadParams defines parameters for GetV1OperationsLogDownload.
type GetV1OperationsLogDownloadParams struct {
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// GetV1OperationsLogStatusParams defines parameters for GetV1OperationsLogStatus.
type GetV1OperationsLogStatusParams struct {
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// GetV1OperationsLogStopParams defines parameters for GetV1OperationsLogStop.
type GetV1OperationsLogStopParams struct {
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// PostV1OperationsLogStartJSONRequestBody defines body for PostV1OperationsLogStart for application/json ContentType.
type PostV1OperationsLogStartJSONRequestBody = LogStart
