// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package models

// Defines values for Connector.
const (
	CloudAzure  Connector = "cloud_azure"
	Packetfence Connector = "packetfence"
)

// Connector defines model for Connector.
type Connector string
