// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package models

import (
	externalRef0 "agentless/infra/model/common"
)

// Inventory defines model for Inventory.
type Inventory = []externalRef0.InventoryItem

// Labels defines model for Labels.
type Labels = []externalRef0.Label

// NetworkConnections defines model for NetworkConnections.
type NetworkConnections struct {
	Network           string   `json:"network"`
	ReachableNetworks []string `json:"reachable-networks"`
}

// NetworkTopology defines model for NetworkTopology.
type NetworkTopology = []NetworkConnections

// GetV1ProviderImportLabelsParams defines parameters for GetV1ProviderImportLabels.
type GetV1ProviderImportLabelsParams struct {
	// Cursor Cursor is the starting position in the result set.
	Cursor *int `form:"cursor,omitempty" json:"cursor,omitempty"`

	// PageSize Maximum number of inventory items per page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetV1ProviderInventoryParams defines parameters for GetV1ProviderInventory.
type GetV1ProviderInventoryParams struct {
	// Cursor Cursor is the starting position in the result set.
	Cursor *int `form:"cursor,omitempty" json:"cursor,omitempty"`

	// PageSize Maximum number of inventory items per page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetV1ProviderTopologyParams defines parameters for GetV1ProviderTopology.
type GetV1ProviderTopologyParams struct {
	// Cursor Cursor is the starting position in the result set.
	Cursor *int `form:"cursor,omitempty" json:"cursor,omitempty"`

	// PageSize Maximum number of network items per page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}
