// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package models

import (
	externalRef0 "agentless/infra/model/common"
)

// Defines values for ConnectionInfoDirection.
const (
	BiDirectional ConnectionInfoDirection = "bi-directional"
	Inbound       ConnectionInfoDirection = "inbound"
	Outbound      ConnectionInfoDirection = "outbound"
	OutboundOnly  ConnectionInfoDirection = "outbound-only"
)

// Defines values for ConnectionInfoEnforcementState.
const (
	Enforcing  ConnectionInfoEnforcementState = "enforcing"
	Monitoring ConnectionInfoEnforcementState = "monitoring"
	RevealOnly ConnectionInfoEnforcementState = "reveal-only"
)

// Defines values for ConnectionInfoEventType.
const (
	Failed     ConnectionInfoEventType = "failed"
	Redirected ConnectionInfoEventType = "redirected"
	Successful ConnectionInfoEventType = "successful"
)

// Defines values for ConnectionInfoIpProtocol.
const (
	Icmp ConnectionInfoIpProtocol = "icmp"
	Tcp  ConnectionInfoIpProtocol = "tcp"
	Udp  ConnectionInfoIpProtocol = "udp"
)

// Defines values for ConnectionInfoIpVersion.
const (
	Ipv4 ConnectionInfoIpVersion = "ipv4"
	Ipv6 ConnectionInfoIpVersion = "ipv6"
)

// Defines values for EnforcementInfoVerdict.
const (
	Alert EnforcementInfoVerdict = "alert"
	Allow EnforcementInfoVerdict = "allow"
	Block EnforcementInfoVerdict = "block"
)

// Defines values for NatInfoType.
const (
	Dnat        NatInfoType = "dnat"
	Snat        NatInfoType = "snat"
	SnatAndDnat NatInfoType = "snat_and_dnat"
)

// ConnectionInfo Aggregated connection information
type ConnectionInfo struct {
	// Count Number of occurrences of the network event.
	Count int64 `json:"count"`

	// DestDomain Domain associated with the destination in the network event (FQDN)
	DestDomain        *string                     `json:"dest-domain,omitempty"`
	DestInventoryItem *externalRef0.InventoryItem `json:"dest-inventory-item,omitempty"`

	// DestIp Destination IP address of the network event.
	DestIp string `json:"dest-ip"`

	// DestPort Destination port number for the network event.
	DestPort int64 `json:"dest-port"`

	// DestProcessInfo Information about a process involved provider the network event.
	DestProcessInfo *ProcessInfo `json:"dest-process-info,omitempty"`

	// DestUsername Username associated with the destination in the network event.
	DestUsername *string `json:"dest-username,omitempty"`

	// Direction Indicates the direction of the network event; bi-directional is reported for two-sided connection; outbound-only - Destination is PaaS resource behind a private endpoint.
	Direction ConnectionInfoDirection `json:"direction"`

	// EndTime End time of the network event.** for aggregated events (epoch in seconds)
	EndTime         int64            `json:"end-time"`
	EnforcementInfo *EnforcementInfo `json:"enforcement-info,omitempty"`

	// EnforcementState Specifies the enforcement level for a network event: 'monitoring' for policy evaluation but allows traffic, and 'reveal only' for data reporting without policy evaluation.
	EnforcementState ConnectionInfoEnforcementState `json:"enforcement-state"`

	// EventType Type of network event that occurred; redirected is used for honeypot
	EventType ConnectionInfoEventType `json:"event-type"`

	// IpProtocol IP protocol used in the network event.
	IpProtocol ConnectionInfoIpProtocol `json:"ip-protocol"`

	// IpVersion IP version used in the network event.
	IpVersion ConnectionInfoIpVersion `json:"ip-version"`

	// NatInfo Information about Network Address Translation.
	NatInfo *NatInfo `json:"nat-info,omitempty"`

	// ReportingEntity Entity that reported the network event.
	ReportingEntity     ReportingEntity             `json:"reporting-entity"`
	SourceInventoryItem *externalRef0.InventoryItem `json:"source-inventory-item,omitempty"`

	// SourceIp Source IP address of the network event.
	SourceIp string `json:"source-ip"`

	// SourceProcessInfo Information about a process involved provider the network event.
	SourceProcessInfo *ProcessInfo `json:"source-process-info,omitempty"`

	// SourceUsername Username associated with the source in the network event.
	SourceUsername *string `json:"source-username,omitempty"`

	// StartTime Start time of the network event.** for aggregated events (epoch in seconds)
	StartTime int64 `json:"start-time"`
}

// ConnectionInfoDirection Indicates the direction of the network event; bi-directional is reported for two-sided connection; outbound-only - Destination is PaaS resource behind a private endpoint.
type ConnectionInfoDirection string

// ConnectionInfoEnforcementState Specifies the enforcement level for a network event: 'monitoring' for policy evaluation but allows traffic, and 'reveal only' for data reporting without policy evaluation.
type ConnectionInfoEnforcementState string

// ConnectionInfoEventType Type of network event that occurred; redirected is used for honeypot
type ConnectionInfoEventType string

// ConnectionInfoIpProtocol IP protocol used in the network event.
type ConnectionInfoIpProtocol string

// ConnectionInfoIpVersion IP version used in the network event.
type ConnectionInfoIpVersion string

// EnforcementInfo defines model for EnforcementInfo.
type EnforcementInfo struct {
	ConnectorDstRuleId  *string                `json:"connector-dst-rule-id,omitempty"`
	ConnectorSrcRuleId  *string                `json:"connector-src-rule-id,omitempty"`
	DcInventoryRevision *int64                 `json:"dc-inventory-revision,omitempty"`
	PolicyRevision      *int64                 `json:"policy-revision,omitempty"`
	RuleId              *string                `json:"rule-id,omitempty"`
	RuleName            *string                `json:"rule-name,omitempty"`
	Verdict             EnforcementInfoVerdict `json:"verdict"`
}

// EnforcementInfoVerdict defines model for EnforcementInfo.Verdict.
type EnforcementInfoVerdict string

// NatInfo Information about Network Address Translation.
type NatInfo struct {
	// DestIp NAT destination IP address.
	DestIp string `json:"dest-ip"`

	// DestPort NAT destination port.
	DestPort int64 `json:"dest-port"`

	// SourceIp NAT source IP address.
	SourceIp string `json:"source-ip"`

	// Type Type of NAT.
	Type NatInfoType `json:"type"`
}

// NatInfoType Type of NAT.
type NatInfoType string

// ProcessInfo Information about a process involved provider the network event.
type ProcessInfo struct {
	// Cmdline Command line arguments used for the process.
	Cmdline *[]string `json:"cmdline,omitempty"`

	// ImagePath Path to the executable of the process.
	ImagePath *string `json:"image-path,omitempty"`

	// ProcessName Name of the process.
	ProcessName string `json:"process-name"`
}

// ReportingEntity Entity that reported the network event.
type ReportingEntity struct {
	// Type Type of the reporting entity such as CloudApp
	Type string `json:"type"`

	// Uuid Unique identifier for the reporting entity such as CloudApp id
	Uuid string `json:"uuid"`
}
