// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package models

// AgentsInfo defines model for AgentsInfo.
type AgentsInfo struct {
	// MacAddresses Known agents MAC addresses without separator
	MacAddresses *[]string `json:"mac-addresses,omitempty"`
}

// PostV1ConsumerAgentsInfoJSONRequestBody defines body for PostV1ConsumerAgentsInfo for application/json ContentType.
type PostV1ConsumerAgentsInfoJSONRequestBody = AgentsInfo

// PutV1ConsumerAgentsInfoJSONRequestBody defines body for PutV1ConsumerAgentsInfo for application/json ContentType.
type PutV1ConsumerAgentsInfoJSONRequestBody = AgentsInfo
