// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package api

import (
	"github.com/gin-gonic/gin"
)

// PostV1OperationsOnboarding operation middleware
func (siw *ServerInterfaceWrapper) PostV1OperationsOnboarding(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1OperationsOnboarding(c)
}

// PostV1OperationsStatus operation middleware
func (siw *ServerInterfaceWrapper) PostV1OperationsStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1OperationsStatus(c)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlersOnboard(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptionsOnboard(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptionsOnboard(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/operations/onboarding", wrapper.PostV1OperationsOnboarding)
	router.POST(options.BaseURL+"/v1/operations/status", wrapper.PostV1OperationsStatus)
}
