// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package api

import (
	"github.com/gin-gonic/gin"
)


// GetV1OperationsInternalConfigMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetV1OperationsInternalConfigMetadata(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1OperationsInternalConfigMetadata(c)
}

// PostV1OperationsInternalInternalConfig operation middleware
func (siw *ServerInterfaceWrapper) PostV1OperationsInternalInternalConfig(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1OperationsInternalInternalConfig(c)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlersConfig(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptionsConfig(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptionsConfig(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/operations/internal/config_metadata", wrapper.GetV1OperationsInternalConfigMetadata)
	router.POST(options.BaseURL+"/v1/operations/internal/internal_config", wrapper.PostV1OperationsInternalInternalConfig)
}
