// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	model "agentless/infra/model/operations"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// GetV1OperationsLogDownload operation middleware
func (siw *ServerInterfaceWrapper) GetV1OperationsLogDownload(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params model.GetV1OperationsLogDownloadParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", c.Request.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1OperationsLogDownload(c, params)
}

// PostV1OperationsLogStart operation middleware
func (siw *ServerInterfaceWrapper) PostV1OperationsLogStart(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1OperationsLogStart(c)
}

// GetV1OperationsLogStatus operation middleware
func (siw *ServerInterfaceWrapper) GetV1OperationsLogStatus(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params model.GetV1OperationsLogStatusParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", c.Request.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1OperationsLogStatus(c, params)
}

// GetV1OperationsLogStop operation middleware
func (siw *ServerInterfaceWrapper) GetV1OperationsLogStop(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params model.GetV1OperationsLogStopParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", c.Request.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1OperationsLogStop(c, params)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlersLog(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptionsLog(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptionsLog(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/operations/log/download", wrapper.GetV1OperationsLogDownload)
	router.POST(options.BaseURL+"/v1/operations/log/start", wrapper.PostV1OperationsLogStart)
	router.GET(options.BaseURL+"/v1/operations/log/status", wrapper.GetV1OperationsLogStatus)
	router.GET(options.BaseURL+"/v1/operations/log/stop", wrapper.GetV1OperationsLogStop)
}
